broker_creds: ~/scripts/awsDB/creds/broker_creds.crypt
db_creds: ~/scripts/awsDB/creds/db_creds.crypt
errormail: james_kirk@starfleet.ufp
ffmpeg_loglevel: error
logfile: testLog.log
loglevel: info
movie_thumbnail_frame: 00:00:15
s3_creds: ~/scripts/awsDB/creds/s3_creds.crypt
test: true
test_broker_creds: ~/scripts/awsDB/creds/test_broker_creds.crypt
test_db_creds: ~/scripts/awsDB/creds/test_db_creds.crypt
test_s3_creds: ~/scripts/awsDB/creds/s3_creds.crypt
thumbnail_extension: .jpg
thumbnail_x_size: '320'
thumbnail_y_size: '240'
